name: Deploy Agrar Dashboard

on:
  push:
    branches:
      - main   # falls dein Haupt-Branch anders heißt, hier anpassen

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install rsync & ssh
        run: sudo apt-get update && sudo apt-get install -y rsync openssh-client

      - name: Deploy public/ to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          # Host-Key akzeptieren
          ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts

          # Sync: public/ -> Serverziel
          rsync -avz --delete ./public/ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
