services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
